### ISSUE TITLE
Markdown/HTML not rendered in short description 

### ISSUE THREAD

**Issue by ghost** [vividvilla/ezhil#41]
On the recent posts - the title is show for a particular post as well as its description: namely 120 characters from the post itself. But it shows the raw html meaning \<p\> and so on..

**Comment by vividvilla** [comment]
This is a limitation as of now, descriptions are not markdown rendered. If we render then its going to break theme, example if post starts with image or quote tag. For now easier for you is to provide custom `description` field in content which will be used instead of first 120 characters.

Will keep this issue open to get suggestions on how to fix this.

**Comment by iromeister** [comment]
Hey, it seems I fixed this issue without knowing about it. ;-)
https://github.com/vividvilla/ezhil/commit/38751fe8623c96bc74d80f2db01712c2be93e515
